#!/bin/sh

progress() {
	for ((k = 0; k <= 19 ; k++))
	do
	    echo -n " >"
	    for ((i = 1 ; i <= k; i++)); do echo -n "###"; done
	    for ((j = i ; j <= 20 ; j++)); do echo -n "   "; done
	    #v=$((k * 10))
	    echo -n "< "
	    echo -n "$k" $'\r'
	    sleep 1
	done
	echo
}

for slide in $(seq 1 20) ; do
	echo
	progress
done
